namespace NameGameCS.Models {
    public static class DefaultNamesList {
        public static List<string> names = new List<string> {
            "Donald Trump",
            "Che Guevara",
            "Pope Francis",
            "Muhammad Ali",
            "Jimmy Carter",
            "Stephen Hawking",
            "Pope John Paul II",
            "Mikhail Gorbachev",
            "Yuri Gagarin",
            "Sylvester Stallone",
            "Steve Jobs",
            "Freddie Mercury",
            "Malcolm X",
            "Elvis Presley",
            "Bob Marley",
            "Fidel Castro",
            "Vladimir Putin",
            "Neil Armstrong",
            "Steven Spielberg",
            "Saddam Hussein",
            "Bruce Lee",
            "Martin Scorsese",
            "Pope Benedict XVI",
            "John Lennon",
            "Prince Philip",
            "Ennio Morricone",
            "Pablo Escobar",
            "Michael Jackson",
            "Boris Yeltsin",
            "Clint Eastwood",
            "Al Pacino",
            "Bill Gates",
            "Muammar Gaddafi",
            "14th Dalai Lama",
            "Marlon Brando",
            "Yasser Arafat",
            "Charles Manson",
            "Kim Jong-il",
            "Stanley Kubrick",
            "Anthony Hopkins",
            "Andy Warhol",
            "Robert De Niro",
            "Luciano Pavarotti",
            "Sean Connery",
            "Morgan Freeman",
            "Jeff Bezos",
            "Martin Luther King Jr.",
            "Arnold Schwarzenegger",
            "Elon Musk",
            "Warren Buffett",
            "Roman Polanski",
            "Jack Nicholson",
            "Pol Pot",
            "George W. Bush",
            "Prince Charles",
            "Noam Chomsky",
            "Danny DeVito",
            "Joe Biden",
            "Dustin Hoffman",
            "Patrick Swayze",
            "Leonard Cohen",
            "Elizabeth II",
            "Marilyn Monroe",
            "Hillary Clinton",
            "Anne Frank",
            "Margaret Thatcher",
            "Cher",
            "Audrey Hepburn",
            "Angela Merkel",
            "Janis Joplin",
            "Judy Garland",
            "Princess Margaret",
            "Tina Turner",
            "Meryl Streep",
            "Maggie Smith",
            "Yoko Ono",
            "Grace Kelly",
            "Princess Diana",
            "Madonna",
            "Barbra Streisand",
            "Judi Dench",
            "Patti Smith",
            "Whitney Houston",
            "Aretha Franklin",
            "Helen Mirren",
            "Sigourney Weaver",
            "J. K. Rowling",
            "Julie Andrews",
            "Gwyneth Paltrow",
            "Cameron Diaz",
            "Sandra Bullock",
            "Margaret Atwood",
            "Anatoly Dyatlov",
            "Angelina Jolie",
            "Muhammad",
            "Genghis Khan",
            "Leonardo da Vinci",
            "Isaac Newton",
            "Ludwig van Beethoven",
            "Alexander the Great",
            "Aristotle",
            "Napoleon",
            "Julius Caesar",
            "Wolfgang Amadeus Mozart",
            "Plato",
            "Jesus",
            "Adolf Hitler",
            "Galileo Galilei",
            "Marco Polo",
            "Socrates",
            "Johann Sebastian Bach",
            "Albert Einstein",
            "Michelangelo",
            "William Shakespeare",
            "Martin Luther",
            "Christopher Columbus",
            "Moses",
            "Archimedes",
            "Abraham",
            "Sigmund Freud",
            "Confucius",
            "Vincent van Gogh",
            "Nicolaus Copernicus",
            "Ferdinand Magellan",
            "Gautama Buddha",
            "Charles Darwin",
            "Karl Marx",
            "Immanuel Kant",
            "Thomas Jefferson",
            "Joseph Stalin",
            "Thomas Edison",
            "Vladimir Lenin",
            "Homer",
            "Pablo Picasso",
            "Nikola Tesla",
            "Antonio Vivaldi",
            "Nelson Mandela",
            "Friedrich Nietzsche",
            "Mahatma Gandhi",
            "Frederic Chopin",
            "J. R. R. Tolkien",
            "Niccola Machiavelli",
            "Hans Christian Andersen",
            "Charlie Chaplin",
            "Salvador Dali",
            "Mary, mother of Jesus",
            "Joan of Arc",
            "Elizabeth I",
            "Marie Curie",
            "Frida Kahlo",
            "Queen Victoria",
            "Marie Antoinette",
            "Nefertiti",
            "Maria Theresa",
            "Agatha Christie",
            "Mary, Queen of Scots",
            "Pocahontas",
            "Anne Boleyn",
            "Catherine the Great",
            "Mary Magdalene",
            "Mother Teresa",
            "Florence Nightingale",
            "Eleanor Roosevelt",
            "Cleopatra",
            "Coco Chanel",
            "Jane Austen",
            "Wallis Simpson",
            "Maria Montessori",
            "Baba Vanga",
            "Virginia Woolf",
            "Eva Braun",
            "Kim Jong-un",
            "Novak Djokovic",
            "Chris Hemsworth",
            "Roger Federer",
            "Mark Zuckerberg",
            "PewDiePie",
            "Prince William",
            "Shia LaBeouf",
            "Usain Bolt",
            "Drake",
            "Daniel Radcliffe",
            "Edward Snowden",
            "Rafael Nadal",
            "Lil Wayne",
            "Avicii",
            "LeBron James",
            "Liam Hemsworth",
            "Eddie Redmayne",
            "Andrew Garfield",
            "Rami Malek",
            "Justin Timberlake",
            "Justin Bieber",
            "Donald Glover",
            "Robert Pattinson",
            "Elijah Wood",
            "Rihanna",
            "Lady Gaga",
            "Natalie Portman",
            "Margot Robbie",
            "Scarlett Johansson",
            "Alicia Keys",
            "Anne Hathaway",
            "Emma Watson",
            "Britney Spears",
            "Amy Winehouse",
            "Avril Lavigne",
            "Keira Knightley",
            "Selena Gomez",
            "Beyonce",
            "Katy Perry",
            "Jessica Alba",
            "Ariana Grande",
            "Jennifer Lawrence",
            "Emilia Clarke",
            "Gal Gadot",
            "Kirsten Dunst",
            "Paris Hilton",
            "Emma Stone",
            "Kristen Stewart",
            "Meghan Markle",
            "Amber Heard",
            "Taylor Swift",
            "Kim Yo-jong",
            "Lindsay Lohan",
            "Megan Fox",
            "Miley Cyrus",
            "Billie Eilish",
            "Mila Kunis",
            "Lana Del Rey",
            "Greta Thunberg",
            "Serena Williams",
            "Kylie Jenner",
            "Dakota Johnson",
            "Nicki Minaj",
            "Adele"
        };
    }
}
